name: MacOS
on:
  push:
    paths:
      - 'QtScrcpy/**'
      - 'keymap/**'
      - 'CMakeLists.txt'
      - '.gitmodules'
      - '.github/workflows/macos.yml'
      - 'ci/generate-version.py'
      - 'ci/mac/**'
  pull_request:
    paths:
      - 'QtScrcpy/**'
      - 'keymap/**'
      - 'CMakeLists.txt'
      - '.gitmodules'
      - '.github/workflows/macos.yml'
      - 'ci/generate-version.py'
      - 'ci/mac/**'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        qt-ver: [5.15.2, 6.5.3]
        include:
          - qt-ver: 5.15.2
            qt-arch-install: clang_64
            build-arch: x64
            runs-on: macos-15-intel
          - qt-ver: 6.5.3
            qt-arch-install: arm64
            build-arch: arm64
            runs-on: macos-14
    env:
      target-name: QtScrcpy
      qt-install-path: ${{ github.workspace }}/Qt/${{ matrix.qt-ver }}
      platform-des: mac

    steps:
      - name: Install Qt5
        if: startsWith(matrix.qt-ver, '5.')
        uses: jurplel/install-qt-action@v4.1.1
        with:
          version: ${{ matrix.qt-ver }}
          arch: ${{ matrix.qt-arch-install }}
          dir: ${{ github.workspace }}/Qt
          cache: true

      - name: Install Qt6
        if: startsWith(matrix.qt-ver, '6.')
        uses: jurplel/install-qt-action@v4.1.1
        with:
          version: ${{ matrix.qt-ver }}
          arch: ${{ matrix.qt-arch-install }}
          dir: ${{ github.workspace }}/Qt
          modules: qtmultimedia
          cache: true

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Build MacOS
        env:
          ENV_QT_PATH: ${{ env.qt-install-path }}
        run: |
          python ci/generate-version.py
          ci/mac/build_for_mac.sh RelWithDebInfo ${{ matrix.build-arch }}

      - name: Get the version
        shell: bash
        id: get-version
        run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Package
        id: package
        env:
          ENV_QT_PATH: ${{ env.qt-install-path }}
        run: |
          publish_name="${{ env.target-name }}-${{ env.platform-des }}-${{ matrix.build-arch }}-Qt${{ matrix.qt-ver }}-${{ steps.get-version.outputs.version }}"
          ci/mac/publish_for_mac.sh ../build ${{ matrix.build-arch }}
          ci/mac/package_for_mac.sh
          mv ci/build/QtScrcpy.app "ci/build/${publish_name}.app"
          mv ci/build/QtScrcpy.dmg "ci/build/${publish_name}.dmg"
          echo "package-name=${publish_name}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.package-name }}
          path: ci/build/${{ steps.package.outputs.package-name }}.dmg

      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ci/build/${{ steps.package.outputs.package-name }}.dmg
          asset_name: ${{ steps.package.outputs.package-name }}.dmg
          tag: ${{ github.ref }}
          overwrite: true