name: Windows

on:
  push:
    paths:
      - 'QtScrcpy/**'
      - 'CMakeLists.txt'
      - '.gitmodules'
      - '.github/workflows/windows.yml'
      - 'ci/generate-version.py'
      - 'ci/win/**'
  pull_request:
    paths:
      - 'QtScrcpy/**'
      - 'CMakeLists.txt'
      - '.gitmodules'
      - '.github/workflows/windows.yml'
      - 'ci/generate-version.py'
      - 'ci/win/**'

jobs:
  build:
    name: Build
    runs-on: windows-2022

    strategy:
      matrix:
        qt-ver: [5.15.2]
        qt-arch: [win64_msvc2019_64, win32_msvc2019]
        include:
          - qt-arch: win64_msvc2019_64
            msvc-arch: x64
            qt-arch-install: msvc2019_64
          - qt-arch: win32_msvc2019
            msvc-arch: x86
            qt-arch-install: msvc2019

    env:
      target-name: QtScrcpy
      vcvarsall-path: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
      vcinstall-path: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC'
      qt-install-path: ${{ github.workspace }}/Qt
      platform-des: win

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v4
        with:
          path: ${{ env.qt-install-path }}
          key: ${{ runner.os }}-Qt-${{ matrix.qt-ver }}-${{ matrix.qt-arch }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.1.1
        with:
          version: ${{ matrix.qt-ver }}
          target: desktop
          arch: ${{ matrix.qt-arch }}
          dir: ${{ env.qt-install-path }}

      - name: Build MSVC
        shell: cmd
        env:
          ENV_VCVARSALL: ${{ env.vcvarsall-path }}
          ENV_QT_PATH: ${{ env.qt-install-path }}/${{ matrix.qt-ver }}
        run: |
          python ci\generate-version.py
          call "ci\win\build_for_win.bat" RelWithDebInfo ${{ matrix.msvc-arch }}

      - name: Get the version
        shell: bash
        id: get-version
        run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Package
        id: package
        shell: powershell
        env:
          ENV_VCVARSALL: ${{ env.vcvarsall-path }}
          ENV_VCINSTALL: ${{ env.vcinstall-path }}
          ENV_QT_PATH: ${{ env.qt-install-path }}/${{ matrix.qt-ver }}
        run: |
          $publishName = "${{ env.target-name }}-${{ env.platform-des }}-${{ matrix.msvc-arch }}-${{ steps.get-version.outputs.version }}"
          cmd.exe /c ci\win\publish_for_win.bat ${{ matrix.msvc-arch }} ..\build\$publishName
          Compress-Archive -Path "ci\build\$publishName" -DestinationPath "ci\build\$publishName.zip" -Force
          echo "package-name=$publishName" >> $env:GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.package-name }}
          path: ci\build\${{ steps.package.outputs.package-name }}

      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ci\build\${{ steps.package.outputs.package-name }}.zip
          asset_name: ${{ steps.package.outputs.package-name }}.zip
          tag: ${{ github.ref }}
          overwrite: true
